model_config:
  model_name: "breast_cancer_diagnosis_v1.0.0"
  model_version: "1.0.0"

  architecture:
    hidden_layers: [24, 24]
    input_dim: 30

    # Possibilities: sigmoid, ReLU
    activation_fn: "sigmoid"
    use_dropout_rate: true

  classes:
    - "B"
    - "M"

training_params:
  test_size: 0.15   # Percentage of data reserved for final testing (never seen during training)
  val_size: 0.15    # Percentage of data used for validation (early stopping, hyperparameter tuning)
  random_state: 42  # Random factor to split data
  epochs: 900
  batch_size: 24
  dropout_rate: 0.0

  # Possibilities: SGD, Adam
  optimizer:
    name: "adam" 
    learning_rate: 0.0001
    weight_decay: 0.0001

  loss_function:
    use_pos_weight: true
    pos_weight: 0.0

  early_stopping:
    patience: 0
    delta: 0.001
    restore_best_weights: false
