model_config:
  model_name: "breast_cancer_diagnosis_v1.2.0"
  model_version: "1.2.0"

  architecture:
    hidden_layers: [24, 24, 24]
    input_dim: 30

    # Possibilities: sigmoid, ReLU
    activation_fn: "sigmoid"
    use_dropout_rate: true

  classes:
    - "B"
    - "M"

training_params:
  test_size: 0.15
  random_state: 42
  epochs: 1200
  batch_size: 4
  dropout_rate: 0.1

  # Possibilities: SGD, Adam
  optimizer:
    name: "SGD" 
    learning_rate: 0.001
    weight_decay: 0.001

  loss_function:
    use_pos_weight: false
    pos_weight: 0.0

  early_stopping:
    patience: 10
    delta: 0.001
    restore_best_weights: false