model_config:
  model_name: "breast_cancer_diagnosis_v1.1.0"
  model_version: "1.1.0"

  architecture:
    hidden_layers: [48, 24, 12]
    input_dim: 30

    # Possibilities: sigmoid, ReLU
    activation_fn: "ReLU"
    use_dropout_rate: true

  classes:
    - "B"
    - "M"

training_params:
  test_size: 0.1
  val_size: 0.1
  random_state: 44
  epochs: 500
  batch_size: 2
  dropout_rate: 0.0

  # Possibilities: SGD, Adam
  optimizer:
    name: "adam" 
    learning_rate: 0.0001
    weight_decay: 0.0

  loss_function:
    use_pos_weight: false
    pos_weight: 0.0

  early_stopping:
    patience: 10
    delta: 0.0001
    restore_best_weights: true